spring.application.name=board


spring.datasource.url=jdbc:postgresql://ep-royal-leaf-aybgowmr-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mM90fGZaqlkX
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.user.name=admin
spring.security.user.password=password


logging.level.org.springframework.security=DEBUG